config/routes.rb
Rr10Team71::Application.routes.draw do
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'

  devise_for :users, :controllers => {:registrations => :registrations}

  resources :comments
  resource :profile

  resources :events do
    member do
      get :crop
    end

    resource :close, only: [:edit, :update], controller: "event_close"

    resources :proposals do
      member do
        get :like
        get :dislike
      end
    end
  end

  root :to => "home#index"

end

app/controllers/event_close_controller.rb
class EventCloseController < ApplicationController
  before_filter :authenticate_user!
  before_filter :event

  def edit
    if event.closed?
      render 'warning_reopen'
    else
      render 'warning_closing'
    end
  end

  def update
    if params[:close] == "true"
      event.close!
      redirect_to event_path(event), notice: t('flash.notice.closed')
    else
      event.reopen!
      redirect_to event_path(event), notice: t('flash.notice.reopened')
    end
  end

  private

  def event
    @event ||= current_user.events.find(params[:event_id])
  end
end

app/views/event_close/warning_closing.html.erb
<div id="new_item">
  <div id="new_item_container">
    <%= image_tag 'event_label.png' %>
    <h3><%= t('.title', event_name: @event.name) %></h3>

    <p>
    <%= t('.closing') %>
    </p>
    <p>
    <%= link_to t('.close'), event_close_path(@event, close: true), method: :put, class: "btn-active" %>
    </p>
  </div>
</div>

app/views/event_close/warning_reopen.html.erb
<div id="new_item">
  <div id="new_item_container">
    <%= image_tag 'event_label.png' %>
    <h3><%= t('.title', event_name: @event.name) %></h3>

    <p>
    <%= t('.reopening') %>
    </p>
    <p>
    <%= link_to t('.reopen'), event_close_path(@event, close: false), method: :put, class: "btn-active" %>
    </p>
  </div>
</div>