config/routes.rb
Rr10Team71::Application.routes.draw do
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'

  devise_for :users, :controllers => {:registrations => :registrations}

  resources :comments
  resource :profile

  resources :events do
    member do
      get :crop
    end

    resource :close, only: [:edit, :update], controller: "event_close"

    resources :proposals do
      member do
        get :like
        get :dislike
      end
    end
  end

  root :to => "home#index"

end

app/models/event.rb
class Event < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, :use => :slugged

  attr_accessor :crop_w, :crop_h, :crop_x, :crop_y, :prod_description

  has_many :proposals, :dependent => :destroy, finder_sql: ->(_) {
    Proposal.with_preloads.where(["proposals.event_id = ?", id]).to_sql
  }, counter_sql: ->(_) {
    Proposal.select('COUNT(*)').where(["proposals.event_id = ?", id]).to_sql
  }

  has_many :comments, :through  => :proposals
  has_many :votes, :through => :proposals
  belongs_to :user

  validates_date :occurs_at, :on => :create, :on_or_after => :today

  validates_presence_of :name, :description, :occurs_at
  validates_associated :user
  validates_length_of :name, :within => 3..150
  validates_length_of :description, :within => 3..400

  before_validation :twitter_has_valid_format

  after_update :reprocess_photo, :if => :cropping?

  attr_accessible :crop_w, :crop_h, :crop_x, :crop_y,
    :picture_cache, :name, :description, :twitter,
    :occurs_at, :url, :user_id, :picture, :prod_description

  mount_uploader :picture, PictureUploader

  class << self
    def opened
      where(closed_at: nil)
    end

    def most_recent
      order("created_at DESC").limit(3)
    end

    def occurs_first
      order("occurs_at ASC")
    end

    def active
      where('occurs_at >= ?', Date.today)
    end
  end

  def as_json(options=nil)
    super({
      :include => {
        :user => { :only => :name, :methods => [:picture] },
        :proposals => {
          :methods => [:votes_count, :comments_count, :acceptance_points,
                       :positive_points, :negative_points],
          :only => Proposal::JSON_ATTRIBUTES,
          :include => {:user => {:only => :name}}
        }
      },
      :methods => [:proposals_count, :votes_count, :comments_count]
    })
  end

  def proposals_count
    proposals.size
  end

  def votes_count
    votes.size
  end

  def comments_count
    comments.size
  end

  def closed?
    closed_at.present?
  end

  def close!
    update_attribute(:closed_at, Time.current)
  end

  def reopen!
    update_attribute(:closed_at, nil)
  end

  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end

  private

  def twitter_has_valid_format
    match = twitter &&
      (twitter.match(/^([a-zA-Z0-9_]{1,15})$/) ||
       twitter.match(/^@([a-zA-Z0-9_]{1,15})$/) ||
       twitter.match(/^(http:\/\/)?www\.twitter\.com\/([a-zA-Z0-9_]{1,15})$/))

    if match
      self.twitter = match[-1]
    elsif twitter.present?
      errors.add(:twitter, :invalid)
    end
  end

  def reprocess_photo
    picture.recreate_versions!
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!, :only => [:new, :create, :update, :edit, :crop]

  respond_to :html, :json, :jsonp

  # GET /events
  # GET /events.xml
  def index
    @events = Event.active.occurs_first.limit(100)
    respond_with @events
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find_by_slug(params[:id])

    # Unfortunately I can't get Rails to preload
    # users because of the crazy SQL involved.
    users_pair = User.find(@event.proposals.pluck('user_id')).map { |u| [u.id, u] }
    @users = Hash[users_pair]
    respond_with @event
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = current_user.events.find_by_slug(params[:id])
  end

  # POST /events
  # POST /events.xml
  def create
    @event = current_user.events.build(params[:event])

    respond_to do |format|
      if verify_recaptcha(:model => @event, :message => 'Please type the captcha correctly') && @event.save
        format.html { redirect_to(@event, :notice => 'Event was successfully created.') }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = current_user.events.find_by_slug(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(@event, :notice => 'Event was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # GET /events/1/crop
  def crop
    @event = current_user.events.find_by_slug(params[:id])
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find_by_slug(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/events_helper.rb
module EventsHelper
  def user_is_owner?(model)
    user = @users.present? ? @users[model.user_id] : model.user
    user_signed_in? && user == current_user
  end
end

app/views/events/_event.html.erb
  <% unless @event.closed? %>
    <%= link_to  image_tag('your_proposal.png'), new_event_proposal_path(@event) %>
  <% end %>

  <div id="proposal">
    <%= link_to image_tag(@event.picture.cropped.url, :class => 'logo', :size => "180x175" ), event_path(@event) %>
    <%= image_tag 'linha.png', :class  => 'linha' %>

    <p><strong><%= @event.name %></strong></p>
    <p><%= truncate(@event.description, :length => 200) %></p>
    <%= image_tag 'linha.png', :class  => 'linha' %>

    <p><strong>Date: </strong><%= l(@event.occurs_at, :format => :long) if @event.occurs_at %></p>
    <p><strong>URL: </strong><%= link_to @event.url, @event.url, :class => 'branco' if @event.url.present? %></p>
    <p><strong>Twitter: </strong>
      <%= link_to @event.twitter, "http://www.twitter.com/#{@event.twitter}", :class => 'branco' if @event.twitter.present?  %>
    </p>

    <%= image_tag 'linha.png', :class  => 'linha' %>

    <p><strong>Organizer: </strong><%= @event.user.name %><br/>
      <%= user_picture(@event.user, :class => 'organizer') %>
    </p>

    <%= image_tag 'linha.png', :class  => 'linha' %>

    <div class="event-social">
      <div class="twit">
        <%= render 'shared/tweet_button', :text => "#{@event.name} is on a call for papers! Check it out. #call4paperz", :url => event_url(@event) %>
      </div>
      <%= render 'shared/facebook_like', :url => event_url(@event) %>
    </div>

  </div>

app/views/events/_form.html.erb
<%= form_for(@event, :html => {:multipart => true}) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %> <small class="vermelho">*</small><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <p class="count_hint" id="name_hint"></p>
  </div>

  <div class="field">
    <%= f.label :description %> <small class="vermelho">*</small><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <p class="count_hint" id="description_hint"></p>
  </div>

  <div class="field">
    <%= f.label :occurs_at %> <small class="vermelho">*</small><br />
    <% if @event.new_record? %>
      <%= f.text_field :occurs_at, :class => 'datepicker' %>
    <% else -%>
      <%= f.text_field :occurs_at, :class => 'datepicker', :value => l(@event.occurs_at, :format => :picker) %>
    <% end %>
  </div>

  <div class="field special">
    <%= f.label :prod_description %><br />
    <%= f.text_field :prod_description, :class => 'twitter' %>
  </div>

  <div class="field">
    <%= f.label :twitter %><br />
    <%= f.text_field :twitter, :class => 'twitter' %>
  </div>

  <div class="field">
    <%= f.label :url, 'Website' %><br />
    <%= f.text_field :url, :class => 'url' %>
  </div>

  <div class="field">
    <%= f.label :picture, 'Picture or logo' %><br />
    <%= f.file_field :picture %>
    <%= f.hidden_field :picture_cache %><br/><br/>
    <p>You can crop the picture later by clicking on "crop", in the event's page.</p>
  </div>

  <%= recaptcha_tags %>

  <div class="actions">

    <% if @event.new_record? %>
      <%= image_submit_tag 'create_event_button.png' %>
    <% else %>
      <%= image_submit_tag 'save.png' %>
    <% end %>
  </div>
<% end %>

<%= javascript_tag do %>
  $(document).ready(function() {
    var descriptionKeycount = new HandleKeycount();
    var nameKeycount = new HandleKeycount();

    descriptionKeycount.init(400, $('#description_hint'), $('#event_description'));
    nameKeycount.init(150, $('#name_hint'), $('#event_name'));

    $.validator.addMethod("twitter", function() {
      var twitter = $('#event_twitter').val();

      return twitter === '' || (twitter.match(/^([a-zA-Z0-9_]{1,15})$/) ||
       twitter.match(/^@([a-zA-Z0-9_]{1,15})$/) ||
       twitter.match(/^(http:\/\/)?www\.twitter\.com\/([a-zA-Z0-9_]{1,15})$/)) !== null;
    }, "Incorrect twitter, enter either youraccount or @youraccount");

    var validator = $("#new_event").validate({
      rules: {
        'event[name]': {required: true, maxlength: 150},
        'event[description]': {required: true, maxlength: 400},
        'event[occurs_at]': "required"
      }
    });
  });
<% end -%>

app/views/events/crop.html.erb
<div id="new_item">
  <div id="crop_original">
    Original:<br/>
    <%= image_tag @event.picture.url, :id => 'crop_target' %>
  </div>
  <div id="crop_previews">
    Current picture:<br/>
    <%= image_tag @event.picture.cropped.url, :size => "180x175" %><br/>

    Preview:<br/>
    <div id="crop_preview_container">
      <%= image_tag @event.picture.url, :id => 'crop_preview', :size => "180x175" %>
    </div>

    <%= form_for(@event) do |f| %>
      <%= f.hidden_field :crop_w, :id => 'photo_crop_w' %>
      <%= f.hidden_field :crop_h, :id => 'photo_crop_h' %>
      <%= f.hidden_field :crop_x, :id => 'photo_crop_x' %>
      <%= f.hidden_field :crop_y, :id => 'photo_crop_y' %>
      <%= f.submit 'Crop' %> or <%= link_to "Cancel", event_path(@event) %>
    <% end %>
  </div>

  <%= javascript_tag do -%>
    function changeCoords(coords) {
        if (parseInt(coords.w) > 0) {
            $("#photo_crop_x").val(coords.x);
            $("#photo_crop_y").val(coords.y);
            $("#photo_crop_w").val(coords.w);
            $("#photo_crop_h").val(coords.h);
        }

        var origWidth = $('#crop_target').width();
        var origHeight = $('#crop_target').height();

        var factorW = 180.0 / coords.w;
        var factorH = 175.0 / coords.h;

        var marginTop = "-" + Math.round(coords.y * factorH);
        var marginLeft = "-" + Math.round(coords.x * factorW);

        var width = Math.round(origWidth * factorW);
        var height = Math.round(origHeight * factorH);

        $('#crop_preview').css({
            marginTop: marginTop + 'px',
            marginLeft: marginLeft + 'px',
            width: width + 'px',
            height: height + 'px'
        });
    }

    $(function(){
        $('#crop_target').Jcrop({
            aspectRatio: 0.97,
            onChange: changeCoords,
            onSelect: changeCoords
        });
    });
  <% end -%>
  <div class="clear"></div>
  <%= link_to "Back to event", event_path(@event) %>
</div>

app/views/events/edit.html.erb
<div id="new_item">
  <div id="new_item_container">
    <%= image_tag 'event_label.png' %>
    <h3>Editing event</h3>

    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<div id="events_list">
  <% if @events.empty? -%>
    <p>There are no events yet. <%= link_to "Be the first to create one!", new_event_path, :class => 'create_button' %></p>
    <br/>
  <% else -%>
	<%= image_tag 'event_list.png' %>
	<p class="sub_vote">A list of events you can proposal to speak or vote in the proposals.</p>
    <%= link_to image_tag('create_transp.png', :title => 'Create new event'), new_event_path, :class => 'create_button' %>
    <ul id="events">
      <% @events.each do |event| %>
        <li class="event_listed">
          <%= image_tag event.picture.cropped.url, :class => 'logo_small' %>
          <div class="event_desc">
            <h1><%= link_to "#{event.name} (#{l(event.occurs_at, :format => :short)})", event %></h1>
            <p>
              <%= truncate(event.description, :length => 100) %>
            </p>
          </div>
          <div class="event_status">
            <span><%= event.proposals_count %></span> <%= pluralize(event.proposals_count, 'proposal').split[1] %>
            <span><%= event.votes_count %></span> <%= pluralize(event.votes_count, 'vote').split[1] %>
            <span><%= event.comments_count %></span> <%= pluralize(event.comments_count, 'comment').split[1] %>
          </div>
        </li>
      <% end %>
    </ul>
    <%= link_to image_tag('create_transp.png', :title => 'Create new event'), new_event_path, :class => 'create_button' %>
  <% end -%>
</div>

app/views/events/new.html.erb
<div id="new_item">
  <div id="new_item_container">
    <%= image_tag 'create_event_label.png' %>
    <h3>Register your event call for papers.</h3>

    <%= render 'form' %>
  </div>
</div>

app/views/events/show.html.erb
<div id="left_bar">
  <%= render :partial => 'events/event' %>
</div>

<div id="proposal_list">
  <% if user_is_owner?(@event) %>
    <div class="event_notice_area">
      <p>
        Administrative tools:
        <strong>
          <%= link_to t('.crop'), crop_event_path(@event) %> |
          <%= link_to t('.edit'), edit_event_path(@event) %> |
          <%= link_to t(".closed_#{@event.closed?}"), edit_event_close_path(@event) %>
        </strong>
      </p>
    </div>
  <% end %>

  <% if @event.closed? %>
    <div class="event_notice_area">
      <p class="alert"><%= t('.closed') %></p>
    </div>
  <% end %>

  <%= image_tag 'prop_vote.png' %>
  <p class="sub_vote">Decide who speaks at the conference!</p>
  <br/>

  <% if @event.proposals.blank? %>
    <span class="yet">This event is ready to receive proposals!</span><br/><br/>
    Tweet this event to your friends so they can submit proposals and spread the word!</spam>
  <br/><br/>
  <%= render 'shared/tweet_button', :text => "#{@event.name} is on a call for papers run! Check it out. #call4paperz", :url => event_url(@event) %>
  <% end %>


  <% @event.proposals.each do |proposal| %>
    <%= render proposal %>
  <%end  %>
</div>


<%= javascript_tag do %>
  $('.ajax_vote').click(function() {
      var thiz = this;

      FetchWithAjax.fetch({
          url: this.href,
          spinner: $(this).parents('.prop').find('.spinner'),
          success: function(data) {
              $(thiz).parents('.prop').replaceWith(data);
          }
      });

      return false;
  });
<% end -%>