config/routes.rb
Rr10Team71::Application.routes.draw do
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'

  devise_for :users, :controllers => {:registrations => :registrations}

  resources :comments
  resource :profile

  resources :events do
    member do
      get :crop
    end

    resource :close, only: [:edit, :update], controller: "event_close"

    resources :proposals do
      member do
        get :like
        get :dislike
      end
    end
  end

  root :to => "home#index"

end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  JSON_ATTRIBUTES = [:id, :name, :created_at, :description, :occurs_at].freeze

  GRACE_PERIOD = 30.minutes

  attr_accessible :acceptance_points

  has_many :votes, :dependent => :destroy
  has_many :comments, :dependent => :destroy

  belongs_to :user
  belongs_to :event, counter_cache: true

  validates_presence_of :name, :description
  validates_associated :user

  validates_length_of :name, :within => 3..150
  validates_length_of :description, :within => 3..400

  attr_protected :event_id

  def self.with_preloads
    select('SUM(v.direction) as acceptance_points, proposals.*').
      joins('LEFT JOIN votes v ON v.proposal_id = proposals.id').
      group('proposals.id').
      order('acceptance_points DESC')
  end

  def acceptance_points
    attributes['acceptance_points'].try(:to_i) || votes.sum('direction')
  end

  def as_json(options=nil)
    super(:include => [:comments, :user], :only => JSON_ATTRIBUTES, :methods => [:comments_count])
  end

  def votes_count
    votes.count
  end

  def comments_count
    comments.count
  end

  def positive_points
    votes.positives.count
  end

  def negative_points
    votes.negatives.count
  end

  def grace_period_left
    grace = (created_at - GRACE_PERIOD.ago).to_i
    grace > 0 ? grace : 0
  end

  def has_grace_period_left?
    grace_period_left > 0
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_filter :event
  before_filter :authenticate_user!, :only => [:create, :new, :update, :destroy, :edit, :dislike, :like]
  before_filter :verify_grace_period, :only => [:update, :edit]
  before_filter :verify_event_closed, only: [:new, :create]

  respond_to :html, :json

  # GET /proposals/1
  # GET /proposals/1.xml
  def show
    @comments = proposal.comments.includes(:user).order("created_at DESC")

    @comment = Comment.new
    @comment.proposal = proposal

    respond_with @proposal
  end

  # GET /proposals/new
  # GET /proposals/new.xml
  def new
    @proposal = Proposal.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @proposal }
    end
  end

  # GET /proposals/1/edit
  def edit
    proposal
  end

  # POST /proposals
  # POST /proposals.xml
  def create
    @proposal = Proposal.new(params[:proposal])
    @proposal.user = current_user
    @proposal.event = event

    respond_to do |format|
      if @proposal.save
        format.html { redirect_to(@event, :notice => 'Proposal was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /proposals/1
  # PUT /proposals/1.xml
  def update
    respond_to do |format|
      if proposal.update_attributes(params[:proposal])
        format.html { redirect_to(@proposal, :notice => 'Proposal was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @proposal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /proposals/1
  # DELETE /proposals/1.xml
  def destroy
    proposal.destroy

    respond_to do |format|
      format.html { redirect_to(proposals_url) }
      format.xml  { head :ok }
    end
  end

  def like
    Vote.like!(proposal, current_user)
    respond_to do |format|
      if request.xhr?
        format.html { render proposal, :layout => false }
      else
        format.html { redirect_to(event_url(event), :notice => 'You liked the proposal.') }
      end
    end
  end

  def dislike
    Vote.dislike!(proposal, current_user)
    respond_to do |format|
      if request.xhr?
        format.html { render proposal, :layout => false }
      else
        format.html { redirect_to(event_url(event), :notice => 'You disliked the proposal.') }
      end
    end
  end

  private
  def event
    @event ||= Event.find params[:event_id]
  end

  def proposal
    @proposal ||= Proposal.find(params[:id])
  end

  def verify_event_closed
    redirect_to event if event.closed?
  end

  def verify_grace_period
    unless proposal.has_grace_period_left?
      redirect_to [event, proposal], :notice => "You cannot edit a proposal after 30 minutes of creation."
    end
  end
end

app/helpers/proposals_helper.rb
module ProposalsHelper

  def proposal_user(proposal)
    if @users.present?
      @users[proposal.user_id]
    else
      proposal.user
    end
  end

  def vote_box(event, proposal, user)
    if user && user.has_vote_for?(proposal)
      image_tag('checked.png', :alt => 'Thanks for voting!').html_safe
    else
      content = ''
      ajax_class = {:class => "ajax_vote"} if user
      content << link_to(image_tag('positive.png', :class => 'thumb thumb_p'), like_event_proposal_path(event, proposal), ajax_class || {})
      content << link_to(image_tag('negative.png', :class => 'thumb'), dislike_event_proposal_path(event, proposal), ajax_class || {})
      content.html_safe
    end
  end

  def render_percentage_bar(percentage)
    if percentage == 50.0
      klass = 'gray'
    elsif percentage > 0
      klass = 'green'
    else
      klass = 'red'
      percentage = percentage.abs
    end

    content_tag :div, :class => 'percentage' do
      content_tag :div, :class => "#{klass}", :style => "width: #{percentage}%" do
        content_tag :span, percentage
      end
    end
  end
end

app/views/proposals/_form.html.erb
<%= form_for([@event, @proposal]) do |f| %>
  <% if @proposal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proposal.errors.count, "error") %> prohibited this proposal from being saved:</h2>

      <ul>
      <% @proposal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %> <small class="vermelho">*</small><br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <p class="count_hint" id="name_hint"></p>
  </div>
  <div class="field">
    <%= f.label :description %> <small class="vermelho">*</small> <br/>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <p class="count_hint" id="description_hint"></p>
  </div>

  <div class="actions">
    <% if @proposal.new_record? %>
      <%= image_submit_tag 'create_event_button.png' %>
    <% else %>
      <%= image_submit_tag 'save.png' %>
    <% end %>
  </div>
<% end %>

<%= javascript_tag do %>

  var descriptionKeycount = new HandleKeycount();
  var nameKeycount = new HandleKeycount();

  descriptionKeycount.init(400, $('#description_hint'), $('#proposal_description'));
  nameKeycount.init(150, $('#name_hint'), $('#proposal_name'));

  $(document).ready(function() {
    var validator = $("#new_proposal").validate({
      rules: {
        'proposal[name]': {required: true, maxlength: 150} ,
        'proposal[description]': { required: true, maxlength: 400 }
      }
    });
  });
<% end -%>

app/views/proposals/_proposal.html.erb
<div class="prop">
  <div class="spinner">
    <%= image_tag 'ajax-loader.gif' %>
  </div>

  <p>
    <strong>
      <%= link_to proposal.name, event_proposal_path(@event, proposal), :class => "prop_link" %>
      <% if user_is_owner?(proposal) %>
        <span id="edit_proposal">
        <%= link_to "(edit)", edit_event_proposal_path(@event, proposal) %>
        </span>
      <% end %>
    </strong>
  </p>
  <%= render_percentage_bar(proposal.acceptance_points) %>
  <p><%= proposal.description %></p>

  <div class="prop_sub">
    <%= user_picture(proposal_user(proposal)) %>
    <small><%= proposal_user(proposal).name %></small>
  </div>

  <%= link_to "#{proposal.comments.size} comments", [@event, proposal], :class => 'com_prop' %>


  <span class="voting_container">
    <%= vote_box(@event, proposal, current_user) %>
  </span>
</div>

app/views/proposals/edit.html.erb
<div id="new_item">
  <div id="new_item_container">
	<p class="sub_add_prop">Editing your proposal</p>
	<br/>

    <%= render 'form' %>

    <p id="proposal_notice"><strong>Please note</strong> you still have <%= distance_of_time_in_words_to_now(Time.now + @proposal.grace_period_left.seconds) %> minutes to make changes.</p>
  </div>
</div>

app/views/proposals/new.html.erb
<div id="new_item">
  <div id="new_item_container">
    <%= image_tag 'add_proposal_label.png' %>
	<p class="sub_add_prop">Submit your proposal for this event.</p>
	<br/>

    <%= render 'form' %>

    <p id="proposal_notice"><strong>Please note</strong> that, after creating your proposal, you have 30 minutes to make changes. After that, you will not be able to modify it.</p>

    <%# <%= link_to 'Back', event_proposals_path %>
  </div>
</div>

app/views/proposals/show.html.erb
<div id="left_bar">
  <%= render :partial => 'events/event' %>
</div>

<div id="proposal_list">
  <%= image_tag 'comments_label.jpg' %>
  <p class="sub_vote">What people think about this proposal.</p>
  <br/>
  <%= render @comment.proposal %>

  <%= render 'comments/form' %>

  <% @comments.each do |comment| -%>
    <%= render comment %>
  <% end -%>
</div>